name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - "release-*"

permissions:
  contents: read

jobs:
  shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Validate shell
        run: ./scripts/ci.sh

  nix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Nix
        uses: NixOS/nix-installer-action@main

      - name: Evaluate NixOS profile
        run: nix flake check --no-build --no-write-lock-file ./platforms/nixos
